### PR TITLE
Fix a bug when the sha file has extra garbage

### PR DESCRIPTION
**Pull request by nicks**

### CODE REVIEW

**Comment by nicks** [comment]
This plugin was very helpful to me, thank you for writing it! I found a little issue while using it and the fix was straightforward enough.

**Comment by ArloL** [comment]
Thanks for the PR, @nicks. Could you perhaps add an integration test that demonstrates your issue? You can copy an existing one e.g. https://github.com/evosec/export-dependencies-maven-plugin/tree/develop/src/it/buck-single-dependency

**Comment by nicks** [comment]
sounds good, test added!

**Comment by ArloL** [comment]
Finally got around to merging your PR. I have done some changes to it to make it more robust against different formats. If you could give me feedback for the 1.0.1-SNAPSHOT version that would be great. Then I can release the 1.0.1!

**Comment by nicks** [comment]
thanks! it works for me!

**Comment by ArloL** [comment]
I have just released 1.0.1: https://travis-ci.org/evosec/export-dependencies-maven-plugin/builds/237793655

**Pull request merged**
